/**
 * GENERATED by scripts/seo/pull-driver-data.mjs — do not edit by hand.
 *
 * What approved drivers agree on about each road, from the backend's
 * /public/route-knowledge. Empty until drivers have answered and the answers are approved.
 * Rerun the script (it shows a diff first, and writes only with --write).
 */
import type { RouteContent } from './index';

export const DRIVER_DATA: Record<string, NonNullable<RouteContent['driver']>> = {};
